import { Recebimento } from '../types';

export const recebimentosMock: Recebimento[] = [
  {
    id: '1',
    guia: '2025001234567',
    conta: 'C001',
    codigo: 'COD001',
    beneficiario: 'Maria Silva Santos',
    dataAtendimento: '2025-11-05',
    codigoProcedimento: '40101012',
    nomeProcedimento: 'Consulta Cardiologia',
    funcao: 'Consulta',
    quantidade: 1,
    custo: 850.00,
    filme: 0,
    honorario: 450.00,
    glosa: 0,
    codGlosa: '',
    total: 1300.00,
    executante: 'Dr. Carlos Mendes',
    localAtendimento: 'Clínica NEOCOR - Unidade Centro',
    prestadorArquivo: 'NEOCOR',
    status: 'recebido',
    formaPagamento: 'PIX',
    instituicao: 'Banco do Brasil',
  },
  {
    id: '2',
    guia: '2025001234568',
    conta: 'C002',
    codigo: 'COD002',
    beneficiario: 'João Pedro Oliveira',
    dataAtendimento: '2025-11-04',
    codigoProcedimento: '40901017',
    nomeProcedimento: 'Ecocardiograma Transtorácico',
    funcao: 'Exame',
    quantidade: 1,
    custo: 1200.00,
    filme: 80.00,
    honorario: 520.00,
    glosa: 0,
    codGlosa: '',
    total: 1800.00,
    executante: 'Dra. Ana Paula Costa',
    localAtendimento: 'Clínica NEOCOR - Unidade Centro',
    prestadorArquivo: 'NEOCOR',
    status: 'recebido',
    formaPagamento: 'Cartão de Crédito',
    instituicao: 'Sicredi',
  },
  {
    id: '3',
    guia: '2025001234569',
    conta: 'C003',
    codigo: 'COD003',
    beneficiario: 'Ana Carolina Ferreira',
    dataAtendimento: '2025-11-03',
    codigoProcedimento: '40901205',
    nomeProcedimento: 'Holter 24 horas',
    funcao: 'Monitoramento',
    quantidade: 1,
    custo: 950.00,
    filme: 0,
    honorario: 350.00,
    glosa: 0,
    codGlosa: '',
    total: 1300.00,
    executante: 'Dr. Roberto Lima',
    localAtendimento: 'Clínica NEOCOR - Unidade Sul',
    prestadorArquivo: 'NEOCOR',
    status: 'pendente',
    instituicao: 'Unimed',
  },
  {
    id: '4',
    guia: '2025001234570',
    conta: 'C004',
    codigo: 'COD004',
    beneficiario: 'Carlos Eduardo Lima',
    dataAtendimento: '2025-11-02',
    codigoProcedimento: '40901018',
    nomeProcedimento: 'Teste Ergométrico',
    funcao: 'Exame',
    quantidade: 1,
    custo: 780.00,
    filme: 50.00,
    honorario: 370.00,
    glosa: 0,
    codGlosa: '',
    total: 1200.00,
    executante: 'Dr. Fernando Souza',
    localAtendimento: 'Clínica NEOCOR - Unidade Centro',
    prestadorArquivo: 'NEOCOR',
    status: 'atrasado',
    instituicao: 'Caixa',
  },
  {
    id: '5',
    guia: '2025001234571',
    conta: 'C005',
    codigo: 'COD005',
    beneficiario: 'Beatriz Costa Almeida',
    dataAtendimento: '2025-11-01',
    codigoProcedimento: '40101012',
    nomeProcedimento: 'Consulta Cardiologia',
    funcao: 'Consulta',
    quantidade: 1,
    custo: 850.00,
    filme: 0,
    honorario: 450.00,
    glosa: 0,
    codGlosa: '',
    total: 1300.00,
    executante: 'Dra. Juliana Martins',
    localAtendimento: 'Clínica NEOCOR - Unidade Norte',
    prestadorArquivo: 'NEOCOR',
    status: 'pendente',
    instituicao: 'Polisaude',
  },
  {
    id: '6',
    guia: '2025001234572',
    conta: 'C006',
    codigo: 'COD006',
    beneficiario: 'Ricardo Souza Martins',
    dataAtendimento: '2025-10-31',
    codigoProcedimento: '40901203',
    nomeProcedimento: 'Cateterismo Cardíaco',
    funcao: 'Procedimento',
    quantidade: 1,
    custo: 8500.00,
    filme: 850.00,
    honorario: 2650.00,
    glosa: 0,
    codGlosa: '',
    total: 12000.00,
    executante: 'Dr. Paulo Santos',
    localAtendimento: 'Hospital NEOCOR',
    prestadorArquivo: 'NEOCOR',
    status: 'recebido',
    formaPagamento: 'Convênio',
    instituicao: 'Unimed',
  },
  {
    id: '7',
    guia: '2025001234573',
    conta: 'C007',
    codigo: 'COD007',
    beneficiario: 'Fernanda Rodrigues',
    dataAtendimento: '2025-10-30',
    codigoProcedimento: '40901206',
    nomeProcedimento: 'MAPA 24 horas',
    funcao: 'Monitoramento',
    quantidade: 1,
    custo: 680.00,
    filme: 0,
    honorario: 320.00,
    glosa: 0,
    codGlosa: '',
    total: 1000.00,
    executante: 'Dr. Marcelo Oliveira',
    localAtendimento: 'Clínica NEOCOR - Unidade Centro',
    prestadorArquivo: 'NEOCOR',
    status: 'pendente',
    instituicao: 'Banco do Brasil',
  },
  {
    id: '8',
    guia: '2025001234574',
    conta: 'C008',
    codigo: 'COD008',
    beneficiario: 'Paulo Henrique Santos',
    dataAtendimento: '2025-10-29',
    codigoProcedimento: '40601021',
    nomeProcedimento: 'Eletrocardiograma',
    funcao: 'Exame',
    quantidade: 1,
    custo: 280.00,
    filme: 0,
    honorario: 120.00,
    glosa: 0,
    codGlosa: '',
    total: 400.00,
    executante: 'Dr. Carlos Mendes',
    localAtendimento: 'Clínica NEOCOR - Unidade Sul',
    prestadorArquivo: 'NEOCOR',
    status: 'atrasado',
    instituicao: 'Sicredi',
  },
  {
    id: '9',
    guia: '2025001234575',
    conta: 'C009',
    codigo: 'COD009',
    beneficiario: 'Mariana Costa Lima',
    dataAtendimento: '2025-10-28',
    codigoProcedimento: '40901019',
    nomeProcedimento: 'Ecocardiograma com Doppler',
    funcao: 'Exame',
    quantidade: 1,
    custo: 1450.00,
    filme: 100.00,
    honorario: 650.00,
    glosa: 0,
    codGlosa: '',
    total: 2200.00,
    executante: 'Dra. Ana Paula Costa',
    localAtendimento: 'Clínica NEOCOR - Unidade Centro',
    prestadorArquivo: 'NEOCOR',
    status: 'recebido',
    formaPagamento: 'PIX',
    instituicao: 'Caixa',
  },
  {
    id: '10',
    guia: '2025001234576',
    conta: 'C010',
    codigo: 'COD010',
    beneficiario: 'Gabriel Alves Pereira',
    dataAtendimento: '2025-10-27',
    codigoProcedimento: '40901207',
    nomeProcedimento: 'Ecocardiograma Transesofágico',
    funcao: 'Exame',
    quantidade: 1,
    custo: 2100.00,
    filme: 150.00,
    honorario: 850.00,
    glosa: 200.00,
    codGlosa: 'GL001',
    total: 2900.00,
    executante: 'Dr. Roberto Lima',
    localAtendimento: 'Hospital NEOCOR',
    prestadorArquivo: 'NEOCOR',
    status: 'pendente',
    instituicao: 'Polisaude',
  },
  {
    id: '11',
    guia: '2025001234577',
    conta: 'C011',
    codigo: 'COD011',
    beneficiario: 'Luciana Pereira Santos',
    dataAtendimento: '2025-10-26',
    codigoProcedimento: '40101012',
    nomeProcedimento: 'Consulta Cardiologia',
    funcao: 'Consulta',
    quantidade: 1,
    custo: 850.00,
    filme: 0,
    honorario: 450.00,
    glosa: 0,
    codGlosa: '',
    total: 1300.00,
    executante: 'Dr. Fernando Souza',
    localAtendimento: 'Clínica NEOCOR - Unidade Sul',
    prestadorArquivo: 'NEOCOR',
    status: 'recebido',
    formaPagamento: 'Cartão de Crédito',
    instituicao: 'Banco do Brasil',
  },
  {
    id: '12',
    guia: '2025001234578',
    conta: 'C012',
    codigo: 'COD012',
    beneficiario: 'Roberto Carlos Souza',
    dataAtendimento: '2025-10-25',
    codigoProcedimento: '40901208',
    nomeProcedimento: 'Cintilografia Miocárdica',
    funcao: 'Exame',
    quantidade: 1,
    custo: 3200.00,
    filme: 250.00,
    honorario: 1050.00,
    glosa: 0,
    codGlosa: '',
    total: 4500.00,
    executante: 'Dra. Juliana Martins',
    localAtendimento: 'Hospital NEOCOR',
    prestadorArquivo: 'NEOCOR',
    status: 'recebido',
    formaPagamento: 'Convênio',
    instituicao: 'Unimed',
  },
  {
    id: '13',
    guia: '2025001234579',
    conta: 'C013',
    codigo: 'COD013',
    beneficiario: 'Patrícia Oliveira Lima',
    dataAtendimento: '2025-10-24',
    codigoProcedimento: '40901017',
    nomeProcedimento: 'Ecocardiograma Transtorácico',
    funcao: 'Exame',
    quantidade: 1,
    custo: 1200.00,
    filme: 80.00,
    honorario: 520.00,
    glosa: 0,
    codGlosa: '',
    total: 1800.00,
    executante: 'Dr. Paulo Santos',
    localAtendimento: 'Clínica NEOCOR - Unidade Norte',
    prestadorArquivo: 'NEOCOR',
    status: 'pendente',
    instituicao: 'Sicredi',
  },
  {
    id: '14',
    guia: '2025001234580',
    conta: 'C014',
    codigo: 'COD014',
    beneficiario: 'André Luiz Ferreira',
    dataAtendimento: '2025-10-23',
    codigoProcedimento: '40901018',
    nomeProcedimento: 'Teste Ergométrico',
    funcao: 'Exame',
    quantidade: 1,
    custo: 780.00,
    filme: 50.00,
    honorario: 370.00,
    glosa: 0,
    codGlosa: '',
    total: 1200.00,
    executante: 'Dr. Marcelo Oliveira',
    localAtendimento: 'Clínica NEOCOR - Unidade Centro',
    prestadorArquivo: 'NEOCOR',
    status: 'atrasado',
    instituicao: 'Polisaude',
  },
  {
    id: '15',
    guia: '2025001234581',
    conta: 'C015',
    codigo: 'COD015',
    beneficiario: 'Camila Rodrigues Costa',
    dataAtendimento: '2025-10-22',
    codigoProcedimento: '40901205',
    nomeProcedimento: 'Holter 24 horas',
    funcao: 'Monitoramento',
    quantidade: 1,
    custo: 950.00,
    filme: 0,
    honorario: 350.00,
    glosa: 0,
    codGlosa: '',
    total: 1300.00,
    executante: 'Dr. Carlos Mendes',
    localAtendimento: 'Clínica NEOCOR - Unidade Sul',
    prestadorArquivo: 'NEOCOR',
    status: 'recebido',
    formaPagamento: 'PIX',
    instituicao: 'Caixa',
  },
  {
    id: '16',
    guia: '2025001234582',
    conta: 'C016',
    codigo: 'COD016',
    beneficiario: 'Eduardo Martins Silva',
    dataAtendimento: '2025-10-21',
    codigoProcedimento: '40901209',
    nomeProcedimento: 'Angiotomografia Coronariana',
    funcao: 'Exame',
    quantidade: 1,
    custo: 2800.00,
    filme: 320.00,
    honorario: 880.00,
    glosa: 0,
    codGlosa: '',
    total: 4000.00,
    executante: 'Dra. Ana Paula Costa',
    localAtendimento: 'Hospital NEOCOR',
    prestadorArquivo: 'NEOCOR',
    status: 'recebido',
    formaPagamento: 'Convênio',
    instituicao: 'Unimed',
  },
  {
    id: '17',
    guia: '2025001234583',
    conta: 'C017',
    codigo: 'COD017',
    beneficiario: 'Juliana Santos Almeida',
    dataAtendimento: '2025-10-20',
    codigoProcedimento: '40601021',
    nomeProcedimento: 'Eletrocardiograma',
    funcao: 'Exame',
    quantidade: 1,
    custo: 280.00,
    filme: 0,
    honorario: 120.00,
    glosa: 0,
    codGlosa: '',
    total: 400.00,
    executante: 'Dr. Roberto Lima',
    localAtendimento: 'Clínica NEOCOR - Unidade Norte',
    prestadorArquivo: 'NEOCOR',
    status: 'pendente',
    instituicao: 'Banco do Brasil',
  },
  {
    id: '18',
    guia: '2025001234584',
    conta: 'C018',
    codigo: 'COD018',
    beneficiario: 'Marcos Paulo Oliveira',
    dataAtendimento: '2025-10-19',
    codigoProcedimento: '40101012',
    nomeProcedimento: 'Consulta Cardiologia',
    funcao: 'Consulta',
    quantidade: 1,
    custo: 850.00,
    filme: 0,
    honorario: 450.00,
    glosa: 0,
    codGlosa: '',
    total: 1300.00,
    executante: 'Dr. Fernando Souza',
    localAtendimento: 'Clínica NEOCOR - Unidade Centro',
    prestadorArquivo: 'NEOCOR',
    status: 'atrasado',
    instituicao: 'Sicredi',
  },
  {
    id: '19',
    guia: '2025001234585',
    conta: 'C019',
    codigo: 'COD019',
    beneficiario: 'Renata Ferreira Santos',
    dataAtendimento: '2025-10-18',
    codigoProcedimento: '40901206',
    nomeProcedimento: 'MAPA 24 horas',
    funcao: 'Monitoramento',
    quantidade: 1,
    custo: 680.00,
    filme: 0,
    honorario: 320.00,
    glosa: 0,
    codGlosa: '',
    total: 1000.00,
    executante: 'Dra. Juliana Martins',
    localAtendimento: 'Clínica NEOCOR - Unidade Sul',
    prestadorArquivo: 'NEOCOR',
    status: 'recebido',
    formaPagamento: 'Cartão de Crédito',
    instituicao: 'Polisaude',
  },
  {
    id: '20',
    guia: '2025001234586',
    conta: 'C020',
    codigo: 'COD020',
    beneficiario: 'Thiago Costa Lima',
    dataAtendimento: '2025-10-17',
    codigoProcedimento: '40901210',
    nomeProcedimento: 'Ressonância Magnética Cardíaca',
    funcao: 'Exame',
    quantidade: 1,
    custo: 3800.00,
    filme: 400.00,
    honorario: 1300.00,
    glosa: 0,
    codGlosa: '',
    total: 5500.00,
    executante: 'Dr. Paulo Santos',
    localAtendimento: 'Hospital NEOCOR',
    prestadorArquivo: 'NEOCOR',
    status: 'recebido',
    formaPagamento: 'Convênio',
    instituicao: 'Unimed',
  },
  {
    id: '21',
    guia: '2025001234587',
    conta: 'C021',
    codigo: 'COD021',
    beneficiario: 'Vanessa Almeida Souza',
    dataAtendimento: '2025-10-16',
    codigoProcedimento: '40901019',
    nomeProcedimento: 'Ecocardiograma com Doppler',
    funcao: 'Exame',
    quantidade: 1,
    custo: 1450.00,
    filme: 100.00,
    honorario: 650.00,
    glosa: 0,
    codGlosa: '',
    total: 2200.00,
    executante: 'Dr. Marcelo Oliveira',
    localAtendimento: 'Clínica NEOCOR - Unidade Norte',
    prestadorArquivo: 'NEOCOR',
    status: 'pendente',
    instituicao: 'Caixa',
  },
  {
    id: '22',
    guia: '2025001234588',
    conta: 'C022',
    codigo: 'COD022',
    beneficiario: 'Wagner Silva Pereira',
    dataAtendimento: '2025-10-15',
    codigoProcedimento: '40901203',
    nomeProcedimento: 'Cateterismo Cardíaco',
    funcao: 'Procedimento',
    quantidade: 1,
    custo: 8500.00,
    filme: 850.00,
    honorario: 2650.00,
    glosa: 500.00,
    codGlosa: 'GL002',
    total: 11500.00,
    executante: 'Dr. Carlos Mendes',
    localAtendimento: 'Hospital NEOCOR',
    prestadorArquivo: 'NEOCOR',
    status: 'atrasado',
    instituicao: 'Banco do Brasil',
  },
  {
    id: '23',
    guia: '2025001234589',
    conta: 'C023',
    codigo: 'COD023',
    beneficiario: 'Adriana Costa Rodrigues',
    dataAtendimento: '2025-10-14',
    codigoProcedimento: '40101012',
    nomeProcedimento: 'Consulta Cardiologia',
    funcao: 'Consulta',
    quantidade: 1,
    custo: 850.00,
    filme: 0,
    honorario: 450.00,
    glosa: 0,
    codGlosa: '',
    total: 1300.00,
    executante: 'Dra. Ana Paula Costa',
    localAtendimento: 'Clínica NEOCOR - Unidade Centro',
    prestadorArquivo: 'NEOCOR',
    status: 'recebido',
    formaPagamento: 'PIX',
    instituicao: 'Sicredi',
  },
  {
    id: '24',
    guia: '2025001234590',
    conta: 'C024',
    codigo: 'COD024',
    beneficiario: 'Bruno Henrique Lima',
    dataAtendimento: '2025-10-13',
    codigoProcedimento: '40901018',
    nomeProcedimento: 'Teste Ergométrico',
    funcao: 'Exame',
    quantidade: 1,
    custo: 780.00,
    filme: 50.00,
    honorario: 370.00,
    glosa: 0,
    codGlosa: '',
    total: 1200.00,
    executante: 'Dr. Roberto Lima',
    localAtendimento: 'Clínica NEOCOR - Unidade Sul',
    prestadorArquivo: 'NEOCOR',
    status: 'pendente',
    instituicao: 'Polisaude',
  },
  {
    id: '25',
    guia: '2025001234591',
    conta: 'C025',
    codigo: 'COD025',
    beneficiario: 'Cristina Alves Santos',
    dataAtendimento: '2025-10-12',
    codigoProcedimento: '40901208',
    nomeProcedimento: 'Cintilografia Miocárdica',
    funcao: 'Exame',
    quantidade: 1,
    custo: 3200.00,
    filme: 250.00,
    honorario: 1050.00,
    glosa: 0,
    codGlosa: '',
    total: 4500.00,
    executante: 'Dr. Fernando Souza',
    localAtendimento: 'Hospital NEOCOR',
    prestadorArquivo: 'NEOCOR',
    status: 'recebido',
    formaPagamento: 'Convênio',
    instituicao: 'Unimed',
  },
  {
    id: '26',
    guia: '2025001234592',
    conta: 'C026',
    codigo: 'COD026',
    beneficiario: 'Daniel Rodrigues Oliveira',
    dataAtendimento: '2025-10-11',
    codigoProcedimento: '40901205',
    nomeProcedimento: 'Holter 24 horas',
    funcao: 'Monitoramento',
    quantidade: 1,
    custo: 950.00,
    filme: 0,
    honorario: 350.00,
    glosa: 0,
    codGlosa: '',
    total: 1300.00,
    executante: 'Dra. Juliana Martins',
    localAtendimento: 'Clínica NEOCOR - Unidade Norte',
    prestadorArquivo: 'NEOCOR',
    status: 'atrasado',
    instituicao: 'Caixa',
  },
  {
    id: '27',
    guia: '2025001234593',
    conta: 'C027',
    codigo: 'COD027',
    beneficiario: 'Elaine Ferreira Costa',
    dataAtendimento: '2025-10-10',
    codigoProcedimento: '40601021',
    nomeProcedimento: 'Eletrocardiograma',
    funcao: 'Exame',
    quantidade: 1,
    custo: 280.00,
    filme: 0,
    honorario: 120.00,
    glosa: 0,
    codGlosa: '',
    total: 400.00,
    executante: 'Dr. Paulo Santos',
    localAtendimento: 'Clínica NEOCOR - Unidade Centro',
    prestadorArquivo: 'NEOCOR',
    status: 'recebido',
    formaPagamento: 'PIX',
    instituicao: 'Banco do Brasil',
  },
  {
    id: '28',
    guia: '2025001234594',
    conta: 'C028',
    codigo: 'COD028',
    beneficiario: 'Fabiana Santos Lima',
    dataAtendimento: '2025-10-09',
    codigoProcedimento: '40901017',
    nomeProcedimento: 'Ecocardiograma Transtorácico',
    funcao: 'Exame',
    quantidade: 1,
    custo: 1200.00,
    filme: 80.00,
    honorario: 520.00,
    glosa: 0,
    codGlosa: '',
    total: 1800.00,
    executante: 'Dr. Marcelo Oliveira',
    localAtendimento: 'Clínica NEOCOR - Unidade Sul',
    prestadorArquivo: 'NEOCOR',
    status: 'pendente',
    instituicao: 'Sicredi',
  },
  {
    id: '29',
    guia: '2025001234595',
    conta: 'C029',
    codigo: 'COD029',
    beneficiario: 'Gustavo Almeida Souza',
    dataAtendimento: '2025-10-08',
    codigoProcedimento: '40901209',
    nomeProcedimento: 'Angiotomografia Coronariana',
    funcao: 'Exame',
    quantidade: 1,
    custo: 2800.00,
    filme: 320.00,
    honorario: 880.00,
    glosa: 0,
    codGlosa: '',
    total: 4000.00,
    executante: 'Dr. Carlos Mendes',
    localAtendimento: 'Hospital NEOCOR',
    prestadorArquivo: 'NEOCOR',
    status: 'recebido',
    formaPagamento: 'Convênio',
    instituicao: 'Unimed',
  },
  {
    id: '30',
    guia: '2025001234596',
    conta: 'C030',
    codigo: 'COD030',
    beneficiario: 'Helena Costa Pereira',
    dataAtendimento: '2025-10-07',
    codigoProcedimento: '40101012',
    nomeProcedimento: 'Consulta Cardiologia',
    funcao: 'Consulta',
    quantidade: 1,
    custo: 850.00,
    filme: 0,
    honorario: 450.00,
    glosa: 0,
    codGlosa: '',
    total: 1300.00,
    executante: 'Dra. Ana Paula Costa',
    localAtendimento: 'Clínica NEOCOR - Unidade Norte',
    prestadorArquivo: 'NEOCOR',
    status: 'atrasado',
    instituicao: 'Polisaude',
  },
];
